name: CI/CD for Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: SSH into EC2 and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          # Navigate to bot directory
          cd /home/ubuntu/Telgrambot
          # Pull latest code
          git pull origin main
          # Install dependencies
          pip3 install -r requirements.txt
          # Restart bot with pm2
          pm2 restart telegram_bot.py || pm2 start telegram_bot.py
        EOF
        rm key.pem